### ISSUE TITLE
DDP模式精度较低

### ISSUE THREAD

**Issue by Senwang98** [DuZzzs/monodleX#2]
@DuZzzs 
Hi，我这边训完DDP分支下的代码，似乎mAP只有11点多，这个比原来的13.72低了很多，不知道大佬在实现的时候有遇到过这个问题吗？
另外，增加monoflex的edge-fusion模块之后，val上面的精度大概是多少呢？
![image](https://user-images.githubusercontent.com/23122139/150638672-12df4a65-84d9-409f-a9b6-2cd4b6888a6d.png)

**Comment by DuZzzs** [comment]
你好，确实DDP会稍低点。加入截断的结果在readme表格中有。

**Comment by Senwang98** [comment]
@DuZzzs
11.x的问题之后我再看看，ddp不应该低两个点

**Comment by DuZzzs** [comment]
期待您的结果  @Senwang98

**Comment by Senwang98** [comment]
@DuZzzs 
抱歉忙其他事补充DDP结果迟了，DDP写的没啥问题我觉得，我重新跑了DDP模式，结果能到14，ddp确实需要调参。
另外我全部浏览完你的代码之后，我依旧有几个小疑问：
1. https://github.com/DuZzzs/monodleX/blob/33555abcdbe6e40555e0285c3d8cbb7669b17f3c/lib/datasets/kitti/kitti_dataset_v2.py#L267，
这里的ry为什么要被注释掉，我发现注释掉的精度会高一点点，但逻辑上不应该是保持这一行吗？
2. 我看DDP branch下，如果还是继续用之前的loss方式，会有3个sub-loss报Nan，随后你换成mse-loss，这一步操作是怎么想到的。
3. monodle的pre-trained模型好像是14.76，支持了monoflex的模块之后+重新计算截断率支持random crop之后好像不如原本的monodle的精度高（在monodistill论文中，@xinzhuma报的精度是15.13）（doge）

感谢老哥分享的代码，学习了

----------------------
补充，我换了v100去训练，精度能提升到15.58，之前从来没这么高过。

**Comment by DuZzzs** [comment]
@Senwang98
你好。尝试解释下，
1. 训练中学习的是alpha，ry做不做操作应该不影响。
2. 报nan的原因是这个batch中没有目标，导致拿到的target为空。这里的mse中input和target是相同变量，目的是让loss为0，无反向梯度。可以直接给0，这块应该是我忘记改了。
3.第一个原因是， 支持阶段目标的代码中没有对kitti数据划分等级去过滤，导致一部分不应该被训练的目标（包括截断目标）被放进去了，测试中类似场景可能就是误报；第二个原因是结构中无nms，结果中对截断目标会出现多个预测框，导致指标会下降。
请问下你的高指标结果做了哪些修改？

**Comment by Senwang98** [comment]
@DuZzzs 
1. 这里我理解一下，后续给你回信。
2. ok，了解了，所以我可以理解为你其实是想直接让loss=0的，但是忘了改所以还是写成了MSE？
3. 你指的等级过滤训练是指easy、hard这种吗？因为kitti的截断确实挺尴尬的，这块我大概能理解你的意思。

关于15.58的问题，我这边提供一个我的模型：
https://drive.google.com/file/d/1_u28HtDGMyrG1MVxdhFjAIgNEYEtDx3r/view?usp=sharing
我的训练过程是直接git clone你的monodlex-main最新代码，ddp精度略低我调参了还是觉得不满意。我是16的batch size * 2 v100训练的，并没有什么修改，config如下：
```
2022-02-16 19:56:48,142   INFO  {'random_seed': 444, 
'log_dir': 'work_dirs/kitti_debug/',

'dataset': {
    'type': 'KITTI_v2', 
    'root_dir': '../../data/KITTI', 
    'batch_size': 16, 
    'use_3d_center': True, 
    'class_merging': False, 
    'use_dontcare': False, 
    'bbox2d_type': 'anno', 
    'meanshape': False, 
    'writelist': ['Car'], 
    'random_flip': 0.5, 
    'random_crop': 0.5, 
    'scale': 0.4, 
    'shift': 0.1
}, 

'model': {
    'type': 'centernet3d', 
    'backbone': 'dla34', 
    'neck': 'DLAUp', 
    'num_class': 3
}, 

'optimizer': {
    'type': 'adam', 
    'lr': 0.00125, 
    'weight_decay': 1e-05
}, 

'lr_scheduler': {
    'warmup': True, 
    'decay_rate': 0.1, 
    'decay_list': [90, 120]
}, 

'trainer': {
    'max_epoch': 140, 
    'gpu_ids': '0, 1', 
    'save_frequency': 10
}, 

'tester': {
    'type': 'KITTI_v2', 
    'mode': 'single', 
    'checkpoint': 'checkpoints/checkpoint_epoch_140.pth', 
    'checkpoints_dir': 'checkpoints', 
    'threshold': 0.2
    }
}
```
mAP结果如下：
```
2022-02-17 02:17:49,968   INFO  ==> Loading from checkpoint 'work_dirs/kitti_debug/checkpoints/checkpoint_epoch_140.pth'
2022-02-17 02:17:50,179   INFO  ==> Done
2022-02-17 02:19:06,684   INFO  ==> Saving ...
2022-02-17 02:19:07,085   INFO  ==> Loading detections and GTs...
2022-02-17 02:19:07,883   INFO  ==> Evaluating (official) ...
2022-02-17 02:19:18,106   INFO  Car AP@0.70, 0.70, 0.70:
bbox AP:96.3705, 88.5285, 87.2624
bev  AP:32.8621, 25.3779, 23.6089
3d   AP:25.6601, 21.2586, 18.2522
aos  AP:95.22, 87.27, 85.11
Car AP_R40@0.70, 0.70, 0.70:
bbox AP:97.7965, 91.9348, 86.8770
bev  AP:28.4764, 21.6623, 18.6656
3d   AP:20.6520, 15.5815, 13.5832
aos  AP:96.58, 90.48, 84.63
Car AP@0.70, 0.50, 0.50:
bbox AP:96.3705, 88.5285, 87.2624
bev  AP:63.3440, 51.0771, 45.5150
3d   AP:59.0918, 45.1106, 42.4834
aos  AP:95.22, 87.27, 85.11
Car AP_R40@0.70, 0.50, 0.50:
bbox AP:97.7965, 91.9348, 86.8770
bev  AP:63.5093, 48.7033, 44.1169
3d   AP:58.4114, 44.6089, 40.1722
aos  AP:96.58, 90.48, 84.63
```

**Comment by DuZzzs** [comment]
对于2，应该是这样。两个写法应该没什么差异，给0更简单。
谢谢。确实高了些。可以理解为batch_size和lr的调整吧？

**Comment by ifanshida** [comment]
您好！我看了这两个问题，但还是没搞明白data结构该如何放置数据集。
我的目录如下：
#ROOT
  |data/
----|KITTI/
------|training/
--------|ImageSets/	
--------|calib/
--------|image_2/
--------|label/
------|testing/
--------|calib/
--------|image_2/

我修改了yaml文件中的root_dir位置为为\monodleX-main\data\KITTI，出现训练第一个echo时，还没开始训练时会报错如下：


  File "../../tools/train_val.py", line 88, in <module>
    main()
  File "../../tools/train_val.py", line 76, in main
    trainer.train()
  File "F:\xiangmu\monodleX-main\lib\helpers\trainer_helper.py", line 73, in train
    self.train_one_epoch()
  File "F:\xiangmu\monodleX-main\lib\helpers\trainer_helper.py", line 98, in train_one_epoch
    for batch_idx, (inputs, targets, _) in enumerate(self.train_loader):
  File "D:\Anaconda3\envs\monodle\lib\site-packages\torch\utils\data\dataloader.py", line 582, in __next__
    return self._process_next_batch(batch)
  File "D:\Anaconda3\envs\monodle\lib\site-packages\torch\utils\data\dataloader.py", line 608, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
AssertionError: Traceback (most recent call last):
  File "D:\Anaconda3\envs\monodle\lib\site-packages\torch\utils\data\_utils\worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "D:\Anaconda3\envs\monodle\lib\site-packages\torch\utils\data\_utils\worker.py", line 99, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "F:\xiangmu\monodleX-main\lib\datasets\kitti\kitti_dataset.py", line 157, in __getitem__
    objects = self.get_label(index)
  File "F:\xiangmu\monodleX-main\lib\datasets\kitti\kitti_dataset.py", line 86, in get_label
    assert os.path.exists(label_file)
AssertionError

想请问大佬这还是我数据集放的位置不对的问题吗？看样子好像是无法正确读取标签，还是想问一下大佬data的结构树是什么样的

**Comment by YinengXiong** [comment]
您好，我使用最新的main分支代码，单卡 `batch_size=16` 训练，训练得到的结果好像和您log里的有一定的差距
![image](https://user-images.githubusercontent.com/23168598/179340419-2bcaa7f9-3b5d-47a6-81bd-2a4445a90f0a.png)

这是我的配置文件
```yaml
random_seed: 444
log_dir: 'work_dirs/test_xyn/'

dataset:
  type: &dataset_type 'KITTI'
  batch_size: 16
  use_3d_center: True
  class_merging: False
  use_dontcare: False
  bbox2d_type: 'anno'   # 'proj' or 'anno'
  meanshape: False      # use predefined anchor or not
  writelist: ['Car']
  random_flip: 0.5
  random_crop: 0.5
  scale: 0.4
  shift: 0.1

model:
  type: 'centernet3d'
  backbone: 'dla34'
  neck: 'DLAUp'
  num_class: 3

optimizer:
  type: 'adam'
  lr: 0.0002
  weight_decay: 0.00001

lr_scheduler:
  warmup: True  # 5 epoches, cosine warmup, init_lir=0.00001 in default
  decay_rate: 0.1
  decay_list: [90, 120]

trainer:
  max_epoch: 140
  gpu_ids: 0
  save_frequency: 10 # checkpoint save interval (in epoch)
  # resume_model: 'checkpoints/checkpoint_epoch_70.pth'


tester:
  type: *dataset_type
  mode: single   # 'single' or 'all'
  checkpoint: 'checkpoints/checkpoint_epoch_140.pth'  # for 'single' mode
  checkpoints_dir: 'checkpoints'  # for 'all' model
  threshold: 0.2  # confidence filter
```
请问为什么会差那么多呀？
